name: Bug report
description: Create a report to help us improve
labels: "bug"

body:
  - type: markdown
    id: description
    attributes:
      value: |
        ## Before posting a feature request
        Search existing [GitHub issues](https://github.com/SpeysideHEP/spey-pyhf/issues) to make sure the issue does not already exist.

        * **Please use [Markdown syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).**
  - type: textarea
    id: system
    attributes:
      label: System Settings
      description: |
        Please copy and paste the output of `spey.about()` function. If you are working on a specific branch please add the name of the branch and last commit ID. The abbreviated commit ID can be found via `git log -n1 --format="%h"` command. To retreive the branch name please use `git rev-parse --abbrev-ref HEAD` command.)
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the behaviour:
          - Please provide a **simplified** and clean code example.
          - If necessary, please provide example data. Note that if GitHub does not accept the data format, it can be uploaded by converting it to `.txt` file.
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected behaviour
      description: |
        A clear and concise description of what you expected to happen.
  - type: textarea
    id: info
    attributes:
      label: Additional information
      description: |
        Add any other context about the problem here.
